# api/openapi.yaml
openapi: 3.0.3

info:
  title: prsk Music API
  description: |
    - **Features**
      - アーティストマスタ管理 - Management artist master
  version: 0.1.0
servers:
  - url: 'http://localhost:8080/btw-api/v1'
    description: development

# ------------------------------------------------------------------------------ #
#  Tags                                                                          #
# ------------------------------------------------------------------------------ #
tags:
  # - name: hello-sekai
  #   description: Get Hello SEKAI !
  - name: artists
    description: |
      アーティストマスタのデータを管理するAPI - Management data of artist master API
      - **Features**
        - アーティスト情報の登録 - Register artist information
        - アーティスト一覧取得 - Get artists list
        - アーティスト情報の更新 - Update artist information
        - アーティスト情報の削除 - Delete artist information

# ------------------------------------------------------------------------------ #
#  Paths                                                                         #
# ------------------------------------------------------------------------------ #
paths:
  # ===== Hello SEKAI ========================================================== #
  # '/view/hello-sekai':
  #   $ref: './api-specs/hello-sekai.yaml#/paths/~1view~1hello-sekai'

  # ===== Artist Master API ==================================================== #
  '/artists':
    $ref: './api-specs/mgt-artist.yaml#/paths/~1artists'
  '/artists/{id}':
    $ref: './api-specs/mgt-artist.yaml#/paths/~1artists~1{id}'
